import "server-only";
import { mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { DeleteObjectCommand, GetObjectCommand, ListObjectsV2Command, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";

export type StoredObject = { body: Buffer; contentType: string };
export type ListedObject = { key: string; lastModified: Date };

export interface ObjectStorage {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
  /** Objects under a folder prefix like "artwork/". Used by the cleanup job. */
  list(prefix: "artwork/" | "profile/"): Promise<ListedObject[]>;
}

/** Keys are generated by us, but validate anyway so a key can never escape the storage root. */
export function assertSafeKey(key: string) {
  if (!/^[a-z0-9-]+\/[A-Za-z0-9_-]+\.(webp|png|jpg|pdf|svg)$/.test(key)) throw new Error("Invalid storage key");
}

/** Development storage on local disk (./.uploads). */
export class LocalStorage implements ObjectStorage {
  constructor(private readonly root = process.env.UPLOADS_DIR ?? path.join(process.cwd(), ".uploads")) {}

  private file(key: string) {
    assertSafeKey(key);
    return path.join(this.root, key);
  }

  async put(key: string, body: Buffer, contentType: string) {
    const file = this.file(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body);
    await writeFile(`${file}.type`, contentType);
  }

  async get(key: string): Promise<StoredObject | null> {
    const file = this.file(key);
    try {
      const [body, contentType] = await Promise.all([readFile(file), readFile(`${file}.type`, "utf8")]);
      return { body, contentType };
    } catch {
      return null;
    }
  }

  async delete(key: string) {
    const file = this.file(key);
    await rm(file, { force: true });
    await rm(`${file}.type`, { force: true });
  }

  async list(prefix: "artwork/" | "profile/"): Promise<ListedObject[]> {
    const dir = path.join(this.root, prefix);
    const names = await readdir(dir).catch(() => [] as string[]);
    const files = names.filter((n) => !n.endsWith(".type"));
    return Promise.all(files.map(async (n) => ({ key: `${prefix}${n}`, lastModified: (await stat(path.join(dir, n))).mtime })));
  }
}

/**
 * S3-compatible storage (AWS S3, Cloudflare R2, …). The bucket must be private;
 * files are served through the app so access rules apply.
 * UNTESTED until S3_* variables are configured.
 */
export class S3Storage implements ObjectStorage {
  private client: S3Client;

  constructor(private readonly bucket: string) {
    this.client = new S3Client({
      region: process.env.S3_REGION ?? "auto",
      endpoint: process.env.S3_ENDPOINT || undefined,
      credentials: {
        accessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
        secretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
      },
    });
  }

  async put(key: string, body: Buffer, contentType: string) {
    assertSafeKey(key);
    await this.client.send(new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: body, ContentType: contentType }));
  }

  async get(key: string): Promise<StoredObject | null> {
    assertSafeKey(key);
    try {
      const res = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: key }));
      if (!res.Body) return null;
      return { body: Buffer.from(await res.Body.transformToByteArray()), contentType: res.ContentType ?? "application/octet-stream" };
    } catch (error) {
      if (error instanceof Error && error.name === "NoSuchKey") return null;
      throw error;
    }
  }

  async delete(key: string) {
    assertSafeKey(key);
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }

  async list(prefix: "artwork/" | "profile/"): Promise<ListedObject[]> {
    const out: ListedObject[] = [];
    let token: string | undefined;
    do {
      const res = await this.client.send(new ListObjectsV2Command({ Bucket: this.bucket, Prefix: prefix, ContinuationToken: token }));
      for (const o of res.Contents ?? []) if (o.Key) out.push({ key: o.Key, lastModified: o.LastModified ?? new Date(0) });
      token = res.IsTruncated ? res.NextContinuationToken : undefined;
    } while (token);
    return out;
  }
}

let storage: ObjectStorage | undefined;

export function getStorage(): ObjectStorage {
  if (storage) return storage;
  if (process.env.STORAGE_PROVIDER === "s3") {
    if (!process.env.S3_BUCKET) throw new Error("STORAGE_PROVIDER=s3 but S3_BUCKET is not set");
    storage = new S3Storage(process.env.S3_BUCKET);
  } else {
    storage = new LocalStorage();
  }
  return storage;
}
